import React from 'react';

import ViewScreen from './../components/ViewScreen.jsx';
import Z from './../components/Z.jsx';
import Pp from './../components/Pp.jsx';
import ChapterStart from './../components/ChapterStart.jsx';

const Creeping = ({ children, num, state }) => (
<div>
<ChapterStart num={num} />
{children}


<Pp>I climbed the rope ladder as soon as I finished puking. I managed to squeeze Wyshwald52's fnucked up body out of his outfit. His wounds looked awful, like gooshburger meat. Everything smelled really weird too. I tried to lift his corpse up by its head but his neck skin was so pappery thin that his whole neck and head ripped straight off of his shoulders. I couldn't carry him up the ladder but I could carry his clothes. I had to leave his nude dismembered parts soaking in the crappy pit.</Pp>
<Pp>The space around the lip of the pit was very bare: a few white plastic tables, unpainted drywall, unpainted cement. I plopped his soiled garb down and scanned the room. I found a sack with all my clothes and valuables along with a sack of frankfurters. I sat on the ground and scarfed down the frankfurters like a slobbery monster. My throat hurt when I swallowed, I could feel the stitches stretch.</Pp>
<Pp>The hallways were very dimly lit. I walked in my dripping smock dragging his soggy clothes leaving red magenta streaks behind me. I listened for footsteps, but it was silent.</Pp>
<Pp>Around a corner I managed to find a restroom. I carefully walked a path around the dimly lit floor putties to the chemical sink, where I washed Wyshwald52's strap jacket and pokey pants. Most of the blood came out. I looked at my reflection in the mirror. In retrospect, I'm hoping it didn't have a ReflectionCam. But I just hadn't seen myself in a while, you know? The clothes fit me pretty well. The sleeves were a little poofy around my arms. My face looked outrageous. My skin was reddish purple. My cheeks were concave. My forehead and chin were covered in cracks and dents. I was missing a nose, it must have gotten crushed completely flat. I looked like a horrible goblin. I left my bloody smock crumpled up in the trash.</Pp>
<Pp>I walked down another hallway, took a right, then another right. Just some locked doors and an empty closet.</Pp>
<Pp>I backtracked and took a left instead. Behind a door on my left I found a place I could charge my celly. I hooked into my celly's UDP port and reactivated my mindchip. I sat and recapped everything into this log for about fifteen <span class="t">*</span>minutes, the whole time until right now. This is right now!</Pp>
<Pp>I'm doing my best to stay focused and present. I don't know where I am. I just escaped execution. They're going to look for me soon. When I think about the bad things my whole body just clenches up and I belch. I'm really dizzy. I just saw a guy's guts, I think it's normal to feel weird after that. I just saw a guy's GUTS. I can't get it out of my mind. I smashed his brain out of his skull.</Pp>
<Pp>Do you feel strange about how much of a piglet I am? I really want the honest truth. It's killing me, not knowing what you think. I get it if you just think I'm slime. You must think I'm a total creep. It feels like I'm performing for you, you're my constant audience, following me everywhere I go. So listen to me right now, OK? I don't want this. Absolutely none of it. I have been sinned against. I am a victim. This is all wrong. You know how freaking nice I am, right? It was him or me. I've tried to be as much of a documentarian as possible. But I don't know if I'm going to be able to get out of here. I don't know where I am! I don't even know where I'm going. And even if I could get out of here, I don't have a speedster. I'm seriously stuck.</Pp>
<Z d={5} spe={55} u="j29" ch={num} o={0} z={state} f l> are u at your desk</Z>
<Z d={40} spe={85} u="j56" ch={num} o={1} z={state} f l> yes, why tho? I dont want to talk to you</Z>
<Z d={10} spe={60} u="j29" ch={num} o={2} z={state} f l> Please I am being Serious it's an EMERGENCY!!</Z>
<Z d={8} spe={70} u="j56" ch={num} o={3} z={state} f l> is it actually?</Z>
<Z d={10} spe={58} u="j29" ch={num} o={4} z={state} f> Yes</Z>
<Z d={5} spe={55} u="j29" ch={num} o={5} z={state}>I'm not comfortable talking about it over the network</Z>
<Z d={9} spe={57} u="j29" ch={num} o={6} z={state} l>someone could be reading our zoips</Z>
<Z d={15} spe={80} u="j56" ch={num} o={7} z={state} f> i already told you</Z>
<Z d={5} spe={75} u="j56" ch={num} o={8} z={state}>i ddon't want to be a part of your life</Z>
<Z d={1} spe={70} u="j56" ch={num} o={9} z={state} l>don't</Z>
<Z d={10} spe={56} u="j29" ch={num} o={10} z={state} f> I'm in danger!!! I'm begging you</Z>
<Z d={3} spe={60} u="j29" ch={num} o={11} z={state}>help me just this once</Z>
<Z d={10} spe={70} u="j29" ch={num} o={12} z={state} l>and I promise you'll never see me again.</Z>
<Z d={1} spe={10} u="SYS" ch={num} o={13} z={state} f> Your account has gotten signed out.</Z>
<Z d={1} spe={10} u="SYS" ch={num} o={14} z={state} l>Would you please sign in again?</Z>
<Z d={15} spe={60} u="j29" ch={num} o={15} z={state} f> username funguyjim29</Z>
<Z d={4} spe={63} u="j29" ch={num} o={16} z={state} l>passcode **tHuNdErDrAgOn91919</Z>
<Z d={1} spe={10} u="SYS" ch={num} o={17} z={state} f> Sign in failed. Did you enter the correct passcode?</Z>
<Z d={9} spe={62} u="j29" ch={num} o={18} z={state} f> username funguyjim29</Z>
<Z d={6} spe={65} u="j29" ch={num} o={19} z={state} l>passcode **tHuNdErDrAgOn19191</Z>
<Z d={1} spe={10} u="SYS" ch={num} o={20} z={state} f l> Sign in failed. Did you enter the correct passcode?</Z>
<Pp>Those are the only two passcodes I ever use. I swear I typed them in correctly. I'm worried that someone in data management might've locked my zoip profile, as part of my resculpting, since it's under my actual name. That means I might not have Drip access either, since that was synced to my zoip profile. Those are probably my two favorite programs! This sucks.</Pp>
<Pp>If I can find a computerior somewhere around here maybe I can at least hook in and communicate with Deward. Deward is miserable in almost every aspect, but it does know a lot of really detailed maps, and I have no idea where I am. I'm worried about walking back into the hallway. What if someone's around the corner? I still smell like marinade and my face looks like scrambled yolks, browned over with scabs, rippled and cracking around muscle. I wonder if there's some way I could wear a mask or ease my stench. It's cold down here. I feel very worried.</Pp>
<Pp>I work up the guts to creep back out into the hallway. My boots are sticky against the floor, squishing splish splosh sounds. I feel the way I feel when I'm about to get a headache. I'm sorry for complaining so much. I feel like a dumb stupid freak.</Pp>
<Pp>On my left there's a cramped room packed with tall stacks of dusty data discs. There are so many of them. I'm trying to get some context but it seems like none of these are labeled. So they're basically garbage. No one's ever going to waste the time to sort through em.</Pp>
<Pp>Diagonal across from that room is a small kitchen. The fridge is pretty well-stocked. I grab a Bblackberry Guaava Queam, a handful of pork knobs, and a bag of frusted corn nuggets, all of which I stuff into the voluminous pockets of my pokey pants. These are really weird pants for a person to wear. What was up with this Wyshwald52 guy? Who did I just kill?</Pp>
<Pp>Around the corner I find what looks to be the man I just killed's computerior room. He has a really big Ultradef, looks like a comfortable keypad too. His account's still signed in. His foam desk chair is miserably sunken in and appears to be deeply stained by many varieties of natural body oils. It feels just slightly damp to sit in. I pull up the console. He seems to have a conversation going with Deward.</Pp>
<ViewScreen num={3} />
<Pp>I wish I had time to look through Wyshwald52's files, I bet they're interesting. I really wonder how anyone on planet earth could ever be Deward's "BUDDY." I'm sure Deward got super frustrated when I neglected to ask how its <span class="t">*</span>day was. That's the kind of stuff that makes it flip out.</Pp>
<Pp>According to the cartographic "YOU ARE HERE" label, I'm on the west end of basement 3. I'm thinking I'll stop by the Resident Chamber on my way down the eastward corridor. Maybe I can find something to cover my face in there. There's a staircase at the end of that corridor that curls up into an amorphous room marked "Exploratory Bio Combs," whatever that means. If this map is up to date, there's a Slide Room at the end of those EBCs. I should be able to take a slide all the way up to The Neck. Fingers crossed that Jumper56 is still in her pod. She'll drive me home. That's what I'm banking on. She's a nice person.</Pp>
<Pp>I strut down the hall on my tip toes. My little mind is on an elliptical rampage I can't transcribe. My muscles are burning and my belly is aching. I keep hearing little clicks and buzzes in the distance. My eyes are blurry. My heart is about to burst out of my ribcage. I think I'm in shock right now. That's probably why things feel muffled. I'm still doing pretty well all things considered. You don't have to worry about me, I'm doing fine.</Pp>
<Pp>This must be Wyshwald52's Resident Chamber. There are strap jackets and pairs of pokey pants hanging in the closet, just like the ones I'm wearing, but in so many patterns and colors. Plus it smells like him, that particular fruity scent, like a rotten diaper. The floral wallpapper is yellowy and peeling, the carpet is gritty like it hasn't been vacuumed in <span class="t">*</span>decades. I don't want to spend a lot of time here, so I prioritize by searching through his dresser first. Perhaps he had goggles, or a mask, or maybe even a balaclava. Anything to change the way my face looks and throw off whatever surveillance algorithms they use for analyzing faces that show up on camera streams.</Pp>
<Pp>Because at this point I'm sure I spend every <span class="t">*</span>second of my life in the frame of a lens. Machines have been tracking me since I was a baby. That's reality. That's how it's always been for forever, but I've never done something bad enough for that to be an especially important concern. They know everything about me. The digital records of all my motives, desires, thoughts, and purchases will persist in dusty server farms *centuries after I take my final breath. All that raw data, more than half of the words I've ever spoken, is currently owned by a loose confederacy of corporations. They know so much about what I'm doing and where I'll be on any given <span class="t">*</span>day. I've seen the information we collect here at Dimples. Every packet is tagged with a georeference. They could easily plug in my coordinates and reduce me to guts with their long outer space guns. I realize I probably sound like a mental freak but I'm being serious.</Pp>
<Pp>It's starting to seem like Wyshwald52 doesn't own many actual items or tools. He mostly just has stuffed plushy animal toys. They're kind of cute but it's still pretty weird. Like, who would want this big stuffed alligator past the age of, like, 4? It's really heavy, uncomfortable to hold. It's not even adorable or anything. Its smile is very unrealistic. Yuck. He also has some froggies and a ducky and a bunny. Those are fine I guess. I just don't like that they're a dead guy's toys, I don't want to touch them. He has large jugs of powerful soap, you can tell by the color of the label, it's dark red. He has odd fluffy wigs. He has half-empty tubes of wart ointment and rash cream. Underneath the tubes, he has a Dimples FaceFriend. I guess I should be using the past tense, he <em>had</em> a Dimples FaceFriend. He can't claim ownership when his dead body is bleeding out in a pit of dark sauce.</Pp>
<Pp>I plug the FaceFriend into the wall socket and it whirrs to life. This must be an earlier model, it's taking much longer to boot up and its visual design is notably less slick. The human face-shaped indentation sinks into the side of the machine. I scroll through the face options on the touch screen. They all honestly look pretty good. But I don't want to stick out, so I select the most basic default facial arrangement ratios available.</Pp>
<Pp>The foamy indentation gargles. I carefully slide my face in.</Pp>
{children}</div>
);

export default Creeping;
