import React from 'react';


import Pp from './../components/Pp.jsx';
import Z from './../components/Z.jsx';
import Snip from './../components/Snip.jsx';

const DrivingToNehers = (props) => (
<div>
{props.children}

<Pp>The city is a neon hell this time of night. Multiple levels of highways are backed up around skyscrapers lit in glaring hues with rail tracks zigzagging vertically between. Each speedster has its own muffling plume of black exhaust. They speed up and slow to a stop, bumper to bumper, jittering forward like segments of a mechanical caterpillar running out of battery. The flow of traffic can cease for *minutes at a time. I don't roast coal every time this purple one in front of me does, because they're about to slam on the breaks. That's a waste of carbon energy. I tend to wait until there's a significant enough gap in front of me before rolling forward, but I'm sure that behavior ticks off the people behind me. If everyone simultaneously chose to stay in place until the traffic cleared, no one would ever move. Our humanoid reflexes are dangerously clunky, and our driving system doesn't accommodate for <Snip bg='red, yellow' content={`The other *day I read an exposé in an internet magazine called Crash: the End of the Self-Navigating Speedster. Apparently much of the publicized dissent for intelligent navigation systems was organized and funded by GRIP, the Guild of Restraint and Immobilization Professionals. Recognizing that self-driving speedsters would dramatically limit both highway collisions and the consequent appeal of restraint and immobilization systems, they funded the production of multi-camera sitcoms, dramas, and soap operas featuring hard-working, blue-collar seatbelt and airbag manufacturers. Case in point: near the end of teevee capsule 2 segment 3 of Each Of My Sons, Norman18 45Speebum takes long pulls of dizzy drink sitting on the hood of a wrecked sedan. Chatham55, his thirteen-year-old boy, was in the front seat of the self-navigating family vehicle when the GPS malfunctioned. It veered into the community brick wall at ninety twentyleaps per *hour. "I sew fifty airbags a *day," Mr. 45Speebum rants. "Only one of those suckers could've kept your grey brains from splattering all over that dam windshield. Only ONE BAG!" He dips his fingers in his child's coagulating blood and spills bubbling dizzy drink down his shirt. "If God wanted speedsters driving independent, I think..." (gurgling, loud thunder overhead) "...I think he'd have given them brains HIMSELF!" He is howling and screaming incoherently as the tears roll down his leathery face.`}>mistakes</Snip>. Any moderate error incurs vehicular damage, monetary loss, and/or bodily harm. I lurch forward and grind to a halt, over and over.</Pp>
<Pp>I hate driving. I hate being wedged in front of and behind and next to people whose one sleepy mistake could grind my body into burger meat. I hate the way my bum feels after sitting for an *hour and a half. I hate seeing their faces as they merge into my lane with their open mouths and sweaty foreheads and unfocused eyes. They look like rubbery tired frogs. They look just as nervous as me. Not encouraging.</Pp>
<Pp>I roll up to the highway intersection. Five lanes on both sides. I almost doink into the rear of the guy in front of me. His bumper sticker says HONK = SCREAM and every half *minute or so he honks. Speedsters race through the intersection while we wait at a red. I'm trying to not think about anything but I keep thinking about not thinking. I feel like I'm swallowing too much air when I breathe. My phone is still vibrating on the passenger's seat. The clock says it's 6:30pt. Looking in the rearview, the swelling really has gone down a lot. I still look purple but not nearly as puffy.</Pp>
<Pp>The sign fades to black and a red dollar sign appears next to some red zeros. I yell at the top of my lungs. A full-throated shout from deep in my gut. I've gotten three super reds this *month, and we're only two *weeks in!</Pp>
<Pp>The zeros climb up to about seventy gold nibs. Two more *minutes pass. I boot up the NeatStreet program on my celly and contribute <Snip bg='red, yellow' content={`Here's the thing, like, I understand that maintaining the roads is an expensive task. But we already have high income tax and sales tax, and we're on Tier 2. Some people around here don't make much. Why would they hold us hostage for funds when the Apex Tier creeps directly above us have castles made of gold? It's senseless. That's why I donate a decent amount, to support those who can't. I don't go overboard or anything, but I contribute more than average.`}>twenty</Snip>.</Pp>
<Pp>I stuff my hands between my knees and shiver. Three more *minutes pass. I put Tulip in park and turn off the coal. The sky is empty darkness.</Pp>
<Pp>A woman carrying a burning torch wanders toward Tulip. Her skin is translucent blue in the flames' glow. Runny saliva trickles down the edge of her tongue. Her face sags like it's melting. Her voice is light and feathery. "Honey! Excuse me honey! Oh honeyboy!" Her eyes are wide like they no longer close. She peers in through the windshield, examining at my body. Her smile almost seems genuine. "I have a story to tell you. Don't you want to hear it?"</Pp>
<Pp>No interaction. That's the rule. I stare straight forward and hold my breath.</Pp>
<Pp>She smashes her raw knuckles against the front left window. She laughs very shrill without pulling her tongue back into her mouth. Her eyes dart up and down. She scrapes her teeth against the glass and claws at the door handle with her sharp fingers.  She shrieks "OPEN THE DOOR!!" Her eyes cross outwards. The sides of buildings light up to display commercials from high end brands. "LET ME IN!!!" I sink down into my seat. She whispers in a raspy seductive trill. "Please let me in, sir." Her teeth are cracked and sharp, jutting out from behind her lips at different angles. "Please let me touch your skin?"</Pp>
<Pp>The pressure in my distorted face hurts terribly. The plastic layer over my skin is so tight. Her fingers rubbing against the window are thin, wiry, and raw. Her body snaps with energy. She furiously slams her fist against the glass. Cracks spider through it. "I WANT TO SWALLOW YOU!!"</Pp>
<Pp>The goal of three hundred gold nibs is finally reached. The sign lights up green and GO. I'm able to make my head totally empty, no thoughts at all. Her laughter fades as I drive away.</Pp>
{props.children}</div>
);

export default DrivingToNehers;
