import React from 'react';


import Pp from './../components/Pp.jsx';
import ChapterStart from './../components/ChapterStart.jsx';
import Snip from './../components/Snip.jsx';

const FirstFloor = ({ children, num, state }) => (
<div>
<ChapterStart num={num} />
{children}

<Pp>The headquarters of Dimples are globular in shape, like a droplet of oil on a flat surface. Its husk is made of thick glass tinted a deep red. On any given <span class="t">*</span>day you can see the silhouettes of people working their hardest inside. The east wing is connected to a monstrous parking deck and remote sections of the campus are accessible via an old tram system. The front lawn is verdant and neat. In the nasty summer you bet I’d sit and eat out on the grass, weather permitting. The green dewy blades are made of a spongy polymer fiber; nowadays they’re frozen solid and crunchy to step on. There’re never any critters or ants or even birds in the vicinity. Just plastic green reaching out so far below the black cloudy heavens. It’s very silent and very still.</Pp>
<Pp>The foyer upon entrance is cavernous! I practically gasped out loud the first time I saw it. The floors and walls are grey marble and the ceiling transparent, showing a view of the floor above but mostly the undersides of people’s dumb old shoes. A marble desk pokes out of the floor in the center of the room for the secretary to sit at. When I arrived ten <span class="t">*</span>minutes early to my first interview she opened the entrance hatch and gave me a great big handshake. I couldn’t make out the name on her name badge. She bubbled over with enthusiasm. “Thank you so much for coming sir! It’s so wonderful to meet you! We are super excited!” She directed me to sit on a flat bench and left the room. She didn’t come back. I had to use my own intuition to figure out where to go. That’s just how it dang ol goes at Dimples. Sometimes I wonder if the bewildering moments of disorganization are, in reality, intricately plotted tests of character. No way to know for sure, but probably not. Big curly blue cursive letters on the foyer’s back wall read “Be your finest. Think the loudest.”</Pp>
<Pp>The door on the right leads to one of the many slide rooms in the complex. It’s special, though, cuz it has up and down slides for every floor, which is super convenient in a pinch. The floor is smooth tile and the ceiling see-through glass. In the mornings around 9 the room gets stuffed with people packed shoulder to shoulder warm and waiting to slide up to their pods. I like standing in that morning mass, listening as everyone quietly whispers to each other about their daily tasks. Every so often if the wait gets to be too long some folks start shoving. It’s best not to stand in the middle of the crowd!</Pp>
<Pp>The first floor bathrooms are the cleanest in the building but they’re still covered in putty <Snip state={state} bg='red, yellow'>“Putty" is slang of recent vintage. It means doo doo. Folks around here eat a lot of genetically modified corn, and the corn contains a lot of really complicated fibres that human tummies can’t digest, so our feces comes out rubbery and sticky. Hence, putty.</Snip> and wizz. The (originally) cream-colored ceramic flooring is stained yellow and always caked with fresh warm man mud. It’s like walking into a large intestine. At least one of the three stalls is always clogged with a mountain of dung and soiled RearWipe Gelpads. When you’ve got this many guys in a single building it’s normal for the men’s restroom to be kind of cruddy, but it still gets on my nerves a little. Some employees flush the urinals over and over until they overflow. They laugh and whistle and push popping wet putties onto the floor and to make matters worse, they stomp em into the tile. I guess I just sometimes wish there were a restroom available where that sort of nonsense wouldn’t be allowed. But I get that’s it’s entirely within their legal right to play with their own choco pies, and I do appreciate that there’s always a path you can follow to avoid stepping on anything solid. Might be hard to believe, but by my second <span class="t">*</span>week there I’d gotten used to it; I block out the stink with my elbow and have my own special technique for wiping clumps off the toilet seat. Plus, the soap stocked in the dispenser has a really nice lavender fragrance, and the hand dryers are the kind that blow hot air really fast. Not too bad!</Pp>
<Pp>The door on the left leads to the company gym. Its window are always fogged up with bodily steam. If it’s quiet you can hear the yells and grunts through the walls. The people that work out in the gym are all at least a leap taller than me. They have hard, tough bodies always glistening with sweat. I wonder how it’d feel to be like that. What's it like to be a big guy? Once I stopped in and watched as they pulled on long ropes that glowed primary colors and jutted out of the floor, walls, and ceiling. They shook on their feet as the ropes pulled back. They winced as rivulets of sweat dripped down their faces. The walls and floors rumbled with energy. Their muscles screamed and spasmed, ready to pop off of their arms and legs. Their expressions were contorted in shapes of pure agony.</Pp>
<Pp>The double doors on the back wall lead into the garden atrium. The grass is always soft and recently cut, and some of the only organic stuff I’ve found in the region. Must’ve been a big investment. They also have an apple tree, a cherry tree, and an orange tree, but those are plastic. A picnic table’s situated between em and a babbling stream runs through a pile of rocks. The table was recently painted white and it’s never given me a splinter. The curved walls render a vibrant vista of cloudless blue skies and rolling hills. The water gurgles and the artificial breeze whistles. The path of small pebbles is lined with papper lilies. No one ever goes in there much.</Pp>
{children}</div>
);

export default FirstFloor;
