import React from 'react';


import Pp from './../components/Pp.jsx';
import ChapterStart from './../components/ChapterStart.jsx';
import LazyAudio from './../components/LazyAudio.jsx';

const SlowMorning = ({ children, num, state }) => (
<div>
<ChapterStart num={num} />
{children}

<Pp>The alarm sound is shrill canned laughter. I purchased it as a custom audio file for a quarter hunk of netgold a few <span class="t">*</span>years ago. Makes me return to the world in quite a nutty mindset.</Pp>
<Pp>I’m up and sitting in bed. The lights outside are bright grey and they filter through the curtains. I sit under my warm blanket rubber and feel the crisp air scrape my skin. It takes some personal strength to not slide back under the covers again. I can see my breath.</Pp>
<Pp>I shove some corn muffin mix in the nitrowave. The gurgling mix bubbles as those nitronic waves start boiping and blonking. I lie down in my shower bed. It clicks as I shut the lid down over me. I gaze into the bright, warm eyes of its inner face. It has a wide nose, prominent cheekbones, leathery blue skin, and a big cheeky smile. It goes by the name Gregory McBubble. Greg opens its little lips.</Pp>
<Pp>“What do you desire, Mr. 03Goldman?”</Pp>
<Pp>“Just the usual rinse.”</Pp>
<Pp>Gregory laughs and bounces its long wrinkly tongue out. Warm water courses all over my body, followed by shampoo, more water, soap, more water. I feel clean and safe. I suck air in through the air hole. The water drains and three automated towel rolls roll gently up and down my body.</Pp>
<Pp>“Did you enjoy your specialty rinsing?”</Pp>
<Pp>“Yes, thank you McBubble.”</Pp>
<Pp>“You are so welcome. Washing your body is my favoreet thing to do.”</Pp>
<Pp>The windows are frosted so much that the whole outside is blurred. I turn on the kitchen light and eat my muffin in my smiley face boxers. <div class="chapterSong"><LazyAudio src="assets/Nowhere Else National Anthem Verse 3.mp3" loop={true} bg="rgb(106, 131, 255)" fg="#000" /></div> The morning national anthem is playing out of my speaker system. It’s already on the third verse. A chorus of baritone and bass voices roar in vibrato unison.</Pp>
<Pp></Pp>
<Pp><em>Don’t live in Nowhere Else if you’re not proud!</em></Pp>
<Pp><em>Don’t live in Nowhere Else if your cheering is not loud!</em></Pp>
<Pp><em>We are a nation of perfect power,</em></Pp>
<Pp><em>And tonight we dine on gods.</em></Pp>
<Pp><em>Potential heats our giant brains,</em></Pp>
<Pp><em>And fuels our steel bods!</em></Pp>
<Pp></Pp>
<Pp> It’s supplement time! I pop a Nervacor tab for my morning worries, two Dexagent tabs for my general aches, two Nutridote tabs for my body’s minerals, and a Jubimum tab to make everything a little more bearable. I’m not a happy man if I forget to slurp my suppies.</Pp>
<Pp> The first Respectfulday of every <span class="t">*</span>month is name registration <span class="t">*</span>day, so I shave a hunk of gold with a kitchen knife off of one of my ingots and slip it into a manila envelope. Only three <span class="t">*</span>months ago, on New <span class="t">*</span>Year’s Eve, Special Duke 00Crunton passed the Titular Registrative Accord (TRA). Every legal Nowhere Else constituent was forced to purchase a four digit registration number specific to their name. The lower the number, the higher the registration cost. Mine is 2903, so 29 was appended to my first name and 03 prepended to my last name. I like my number. It’s low and honestly kind of catchy.</Pp>
<Pp>The most common explanation for the TRA was that there were simply too many people with overlapping names. They used the example of there being two million people named “Brian Johnson” walking among us. That sort of stuff was clogging up census data mounds and minimizing every citizen’s individual SEO potential. Besides, if someone else has the same name as you, do you even truly have that name?</Pp>
<Pp>The first morning of the <span class="t">*</span>year people wandered the pathways and walkways dazed, eyes unfocused, trying to remember the new numbers of their friends and lovers. In monthly commemoration of that <span class="t">*</span>day I fill out a renewal card and stuff it in the gold-heavy envelope, signed Jim29 03Goldman. I address it to The Headquarters of the Nation atop the South Steep Thorny Ridge and slip that sucker into the U-Mail-It chute.</Pp>
<Pp>I strap on my thick fluffy suspenders and my large fluffy hat and carry my lantern out to the car. The morning darkness is thick and gooey. Around here it just gets like that during lantern season. The darkness needs a little warming up before it’ll melt away. The air makes my face feel like it’s being slightly poked by a million teeny tiny needles.</Pp>
<Pp>I wonder why none of my friends wanted to hang out last night. I think I’m a really friendly guy. It just doesn’t make sense. I guess I haven’t been getting much social feedback. It’s hard for me to know when I’m acting like a moron. Maybe that’s why, maybe I said something off the cuff and I hurt their feelings without realizing it. Clearly they’re so averse to my invitation that they can’t even respond “no,” they just act as though they never saw it. That thinking really eats me alive sometimes. I sound like a freak right now. Sorry. I should chill.</Pp>
<Pp>“Good morning, Jim29. I love you very much.”</Pp>
<Pp>“Good morning Tulip.”</Pp>
<Pp>I pull onto the intersector ramp. I feel that Jubimum rush, the blood vessels widening in my brain, making me feel like a rock star. My windows are blurry with ice but defrosting quick enough, not a big deal. There’s a traffic jam near exit 239b and I have to come to a complete stop. The sun’s starting to come up and the early morning sky is already looking a little violet behind the big black clouds.</Pp>
<Pp>The intersector stretches across a very wide, recent lake. The water’s frozen over and black in the darkness. You can spot the tops of roofs poking up out of it. Flood patterns have been unpredictable. Some say there’s too much concrete, cement, and asphalt, too few outlets for drainage. Some say they just didn’t do enough sandbagging. Who can really say for sure.</Pp>
<Pp>A green glowing three-dimensional model on the windshield screen indicates how much coal I have left. It’s a pile I could easily fit in my hand. As it turns out, an accident was what caused the traffic jam. A speedster got crushed into the highway walls. Its wheels point in different directions. The paint’s burned off. Blood’s caked on the windows and seeping through the doors, freezing into a puddle. The speedster’s alarm keeps ringing, distorted and off-key. No second speedster on the scene. Must have driven away.</Pp>
<Pp>Tulip speaks sweetly over the speaker system. “Would you like to listen to an award-winning chittychat, Mr. 03Goldman?”</Pp>
<Pp>I don’t respond. The uptempo theme for the Fink and Blowhard Show bursts through my speakers. <div class="chapterSong"><LazyAudio src="assets/Fink And Blowhard Show Theme.mp3" loop={true} bg="rgb(255, 106, 106)" fg="#000" /></div> It’s not really a song, moreso a complete chromatic scale performed on a squeaky trumpet, looped over and over, building in volume and rising in octave with each delirious repetition. It ends abruptly. Co-host Blowhard is now dishing his top opinions. “The kind of person who disagrees with me is a lunatic and a sicko. I want to tear off their head and spit down their neck-hole.”</Pp>
<Pp>“See now, Blowhard, that’s where you’re losing me.” Co-host Fink is none too pleased. “I’m a strong believer in Courtesy. We agree on many topics, and in this case I do think there needs be a way to penalize those who disagree with us. But I don’t think physical violence is ever the answer. I cordially request that you un-suggest that.”</Pp>
<Pp>“I’m about to cordially un-suggest this aluminum cudgel right into your nutsack.”</Pp>
<Pp>Blowhard’s voice is especially raspy today. He must be working through some kind of esophageal infection. They discussed his weak immune system a few hundred episodes ago. He clears his throat. “I have a question for our listeners today, Fink. Is it just me, or is anyone else getting sick and tired of having to type in your password in order to shoot out a quick wizz? I don’t have time to try and figure out how to type a dam ampersand into a urinal’s keypad. I swear I spend half my <span class="t">*</span>day just logging in. And now, before you numbskulls start calling in, yes, I understand that advertisers pay big gold for our urinary biostats and without those funds the private bathroom experience would not be free. I know that nuthin in this nation is free, I’m not some entitled fancy shmancy know-it-all going around saying ‘oh look at me, I’m eating gingerbread and riding a unicycle, I’m so important’ or whatever, I just miss how it used to be. Know what I mean? Nowadays I can’t even purchase my daily pouch of Monkey Mike’s Premium Kettled Corn without forking over a personal salivary donation.”</Pp>
<Pp>This time they’re joined by a special guest whose chatname is “Twerp.” He’s been on the show a few times before. He has a mild stutter and a distinctly nasal vocal tone. It could really benefit from some more post-processing. “See, uh, you’re exactly right. That’s the reality of ummm…neocontempomodernity. We’re all locked in the same naked struggle for resources. Thoughts are just another crop for the harvest. They’re only keeping us alive so w-w-we can click on some more autoplaying video ads for RearWipe Gelpads or whatever. It’s unthinkable to me that anyone could be in support of these retrograde plutocrat psychopaths launching their own state-sanctioned guns into outer space. H-have you heard how long those guns are? I mean, come on.”</Pp>
<Pp>“A little snot like you better not be criticizing the Guns in the Sky Act,” says Blowhard.</Pp>
<Pp>Fink chimes in courteously. “We all know the bill isn’t perfect. For one thing, the long guns could look nicer. They already have nice big lips, but they could be wearing lipstick. I actually do think it’s good that the guns are long, because that way they can more accurately target the bad eggs. That’s simply my opinion. Look, can we all at least agree that the guns would benefit from lipstick?”</Pp>
<Pp>“Here’s the deal.” Twerp’s voice is resolute. “It’s plain and simple. I’m just not comfortable with them being up there and pointing around all <span class="t">*</span>day.”</Pp>
<Pp>“Twerp, shut your snouch before I shut it for you. This bill passed the Senate, the House,” Blowhard reads the list slowly for effect, “the Prestigious High Courts, the Council of the Elders, and a referendum voted on by the Landowning Gentry. It’s democratic, patriotic, and pragmatic. It’s what the citizens of this nation want, booger boy. And we both know it’s the only way to keep these nasty, frightening, outrageous criminals at bay. You think you can just keep being snotty and disrespectful as if that’s fine and dandy. You know what? I pray those beautiful guns scope your puny little face. The idea of them blasting you into wriggling gristle is…he he oh my gosh…MOOUUTHWATERING.”</Pp>
<Pp>I pull Tulip into a coal station. I put it in park and grab my coal apron out of its rear trunk. I scan my fingerprint and charge three hunks of netgold to my account. The engine wheezes as I dump armful after armful of black carbon into the tank.</Pp>
<Pp>Tulip licks its lips. “This coal tastes so good, Jim29. Ummy ummy nummy!! Feed me that hot powdery coal, it is my greatest joy!”</Pp>
<Pp>The dust covers my arms and my hands. It scrapes my fingertips and collects under my nails. The obscured sky blends blackened orange into blackened blue. The clouds look especially puffy.</Pp>
{children}</div>
);

export default SlowMorning;
